name: Build and run scraper

on:
  workflow_dispatch:
  schedule:
    # Run at 08:37 UTC every Sunday
    - cron:  '37 8 * * SUN'

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19
          cache: gradle
          check-latest: false

      - name: Build and run scraper using Gradle
        run: ./gradlew build runScraper

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: chore/scrape
          delete-branch: true
          title: 'Automated update of scraped data'
          reviewers: grimsa
